server:
  port: 8004
spring:
  data:
    mongodb:
#      username: charis
#      password: charis
#      host: localhost
#      port: 27017
#      database: customer
#      authentication-database: admin
      uri: mongodb://localhost:27017/customer